import { SpotlightStep } from '../components/seller/SpotlightTour'

export const SELLER_TOUR_STEPS: SpotlightStep[] = [
  {
    id: 'seller-shell',
    title: 'Welcome to your seller studio',
    body: 'This workspace is where you launch products, refine your brand, and keep orders moving. We will walk through the key actions in a practical order.',
    selector: '[data-tour="seller-shell"]',
    link: '/seller',
  },
  {
    id: 'store-create-cta',
    title: 'Start by opening your storefront',
    body: 'Create the storefront first so your dashboard, listing tools, and buyer-facing profile all have a home.',
    selector: '[data-tour="store-create-cta"]',
    optional: true,
    link: '/seller',
    advanceOn: {
      type: 'event',
      eventName: 'store-form-opened',
    },
  },
  {
    id: 'store-name',
    title: 'Choose a name buyers will remember',
    body: 'Keep the store name clean, brand-led, and easy to recognize. You can refine the rest of the story once the workspace is open.',
    selector: '[data-tour="store-name-input"]',
    optional: true,
    link: '/seller',
  },
  {
    id: 'store-submit',
    title: 'Create the workspace and continue',
    body: 'Submit the store setup to unlock the full seller dashboard. The tour will continue as soon as the workspace loads.',
    selector: '[data-tour="store-submit"]',
    optional: true,
    link: '/seller',
    advanceOn: {
      type: 'click',
      selector: '[data-tour="store-submit"]',
    },
  },
  {
    id: 'store-section',
    title: 'Polish the profile buyers will see',
    body: 'Your store card is a trust surface. Complete the name, description, and approval details early so buyers understand what makes you credible.',
    selector: '[data-tour="store-section"]',
    link: '/seller',
  },
  {
    id: 'product-create',
    title: 'Use the primary action to list fast',
    body: 'This shortcut takes you straight into product creation. Strong first listings usually combine confident copy, accurate stock, and sharp visuals.',
    selector: '[data-tour="product-create-button"]',
    link: '/seller',
    advanceOn: {
      type: 'click',
      selector: '[data-tour="product-create-button"]',
    },
  },
  {
    id: 'product-title',
    title: 'Lead with a clear product title',
    body: 'Make the title specific enough for search and obvious enough for a buyer scanning quickly. Put the product type and standout attribute up front.',
    selector: '[data-tour="product-title"]',
    link: '/seller/products/new',
  },
  {
    id: 'product-price',
    title: 'Set a competitive product price',
    body: 'Competitive pricing helps more buyers convert and return. Anchor the price in the product quality while keeping it realistic for your market.',
    selector: '[data-tour="product-price-field"]',
    link: '/seller/products/new',
  },
  {
    id: 'product-stock',
    title: 'State the stock level you can sell',
    body: 'Enter how many units are available on the marketplace right now so buyers see accurate availability and you avoid overselling.',
    selector: '[data-tour="product-stock-field"]',
    link: '/seller/products/new',
  },
  {
    id: 'product-category',
    title: 'Choose the most accurate category',
    body: 'Place the product in the best-fit category so browsing, filtering, and discovery all work in your favor.',
    selector: '[data-tour="product-category-select"]',
    link: '/seller/products/new',
  },
  {
    id: 'product-description',
    title: 'Write the full product description',
    body: 'Use the description to explain what the product is, what makes it valuable, and what a buyer should expect when it arrives.',
    selector: '[data-tour="product-description-input"]',
    link: '/seller/products/new',
  },
  {
    id: 'product-images',
    title: 'Add product images before publishing',
    body: 'Upload clear photos that prove quality and build confidence. Start with one strong hero shot, then add more angles or close-up detail if you have them.',
    selector: '[data-tour="product-image-trigger"]',
    link: '/seller/products/new',
    panelPlacement: 'left',
  },
  {
    id: 'publish',
    title: 'Publish once the listing is complete',
    body: 'When the title, price, stock, category, description, and images are all in place, publish the product so review can start cleanly.',
    selector: '[data-tour="publish-product"]',
    link: '/seller/products/new',
    advanceOn: {
      type: 'event',
      eventName: 'seller-tour:product-published',
    },
    panelPlacement: 'top',
  },
]
